//! Ghost bridge — sync cognition context to AI coding assistant memory directories
//!
//! Writes a markdown context file with user model summaries, belief stats,
//! and cognitive patterns to Claude Code, Cursor, Windsurf, and Cody memory dirs.
//! Uses FNV-1a content hashing to skip redundant writes.

use std::fs;
use std::io::Write;
use std::path::PathBuf;

// ── Client detection ────────────────────────────────────────────

struct ClientDir {
    dir: PathBuf,
    filename: &'static str,
}

fn detect_clients() -> Vec<ClientDir> {
    let home = match dirs::home_dir() {
        Some(h) => h,
        None => return Vec::new(),
    };

    let candidates: &[(&str, &str)] = &[
        (".claude/memory", "COGNITION_CONTEXT.md"),
        (".cursor/memory", "agentic-cognition.md"),
        (".windsurf/memory", "agentic-cognition.md"),
        (".sourcegraph/cody/memory", "agentic-cognition.md"),
    ];

    let mut clients = Vec::new();
    for (rel, filename) in candidates {
        let parent = home.join(rel).parent().unwrap_or(&home).to_path_buf();
        let dir = home.join(rel);
        if parent.is_dir() {
            let _ = fs::create_dir_all(&dir);
            if dir.is_dir() {
                clients.push(ClientDir { dir, filename });
            }
        }
    }
    clients
}

// ── FNV-1a hash ─────────────────────────────────────────────────

fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

// ── Ghost bridge struct ─────────────────────────────────────────

pub struct GhostBridge {
    clients: Vec<ClientDir>,
    last_hash: u64,
}

impl GhostBridge {
    /// Detect AI coding assistant directories and create bridge.
    /// Returns None if no clients are found.
    pub fn new() -> Option<Self> {
        let clients = detect_clients();
        if clients.is_empty() {
            return None;
        }
        tracing::info!("Ghost bridge active for {} client(s)", clients.len());
        Some(Self {
            clients,
            last_hash: 0,
        })
    }

    /// Sync cognition context to all detected client directories.
    /// Skips write if content hash is unchanged.
    pub fn sync(&mut self, query: &agentic_cognition::QueryEngine) {
        let content = build_cognition_context(query);
        let hash = fnv1a(content.as_bytes());
        if hash == self.last_hash {
            return;
        }
        self.last_hash = hash;

        for client in &self.clients {
            let target = client.dir.join(client.filename);
            let tmp = target.with_extension("md.tmp");
            if let Ok(mut f) = fs::File::create(&tmp) {
                if f.write_all(content.as_bytes()).is_ok() && f.flush().is_ok() {
                    let _ = f.sync_all();
                    let _ = fs::rename(&tmp, &target);
                }
            }
        }
    }
}

// ── Build markdown context ──────────────────────────────────────

fn build_cognition_context(query: &agentic_cognition::QueryEngine) -> String {
    let mut md = String::with_capacity(4096);
    md.push_str("# AgenticCognition — Live Context\n\n");
    md.push_str("> Auto-generated by ghost bridge. Do not edit.\n\n");

    // Model overview
    let models = match query.list_models() {
        Ok(m) => m,
        Err(_) => {
            md.push_str("_No models loaded._\n");
            return md;
        }
    };

    md.push_str(&format!("**Models:** {}\n\n", models.len()));

    if models.is_empty() {
        md.push_str("_No user models yet. Use `cognition_model_create` to start._\n");
        return md;
    }

    // Models table
    md.push_str("## User Models\n\n");
    md.push_str("| Model | Stage | Beliefs | Evidence | Health |\n");
    md.push_str("|-------|-------|---------|----------|--------|\n");

    for (i, model_id) in models.iter().enumerate() {
        if i >= 20 {
            md.push_str(&format!(
                "| _...and {} more_ | | | | |\n",
                models.len() - 20
            ));
            break;
        }

        let id_short = &model_id.to_string()[..8];

        // Get portrait for this model
        if let Ok(portrait) = query.get_portrait(model_id) {
            let health = query
                .get_vitals(model_id)
                .map(|v| format!("{:.0}%", v.health * 100.0))
                .unwrap_or_else(|_| "?".into());

            md.push_str(&format!(
                "| `{}…` | {:?} | {} | {} | {} |\n",
                id_short,
                portrait.model.lifecycle_stage,
                portrait.belief_count,
                portrait.model.evidence_count,
                health,
            ));
        } else {
            md.push_str(&format!("| `{}…` | ? | ? | ? | ? |\n", id_short));
        }
    }
    md.push('\n');

    // Per-model cognitive snapshot (first 5 models)
    for model_id in models.iter().take(5) {
        let id_short = &model_id.to_string()[..8];
        md.push_str(&format!("### Model `{}…`\n\n", id_short));

        // Belief domains
        if let Ok(beliefs) = query.list_beliefs(model_id) {
            let mut domain_counts: std::collections::HashMap<String, usize> =
                std::collections::HashMap::new();
            for b in &beliefs {
                *domain_counts.entry(format!("{}", b.domain)).or_insert(0) += 1;
            }
            if !domain_counts.is_empty() {
                md.push_str("**Belief domains:** ");
                let parts: Vec<String> = domain_counts
                    .iter()
                    .map(|(d, c)| format!("{} ({})", d, c))
                    .collect();
                md.push_str(&parts.join(", "));
                md.push_str("\n\n");
            }
        }

        // Shadow map summary
        if let Ok(shadow) = query.get_shadow_map(model_id) {
            if shadow.shadow_beliefs.len() + shadow.projections.len() + shadow.blindspots.len() > 0
            {
                md.push_str(&format!(
                    "**Shadows:** {} beliefs, {} projections, {} blindspots\n\n",
                    shadow.shadow_beliefs.len(),
                    shadow.projections.len(),
                    shadow.blindspots.len(),
                ));
            }
        }

        // Drift summary
        if let Ok(drift) = query.get_drift_timeline(model_id) {
            if drift.events.len() + drift.metamorphoses.len() + drift.growth_rings.len() > 0 {
                md.push_str(&format!(
                    "**Drift:** {} events, {} growth rings, {} metamorphoses\n\n",
                    drift.events.len(),
                    drift.growth_rings.len(),
                    drift.metamorphoses.len(),
                ));
            }
        }

        // Fingerprint
        if let Ok(Some(fp)) = query.get_fingerprint(model_id) {
            md.push_str(&format!(
                "**Pattern fingerprint:** risk={:.2}, intuition={:.2}, time_horizon={:.2}\n\n",
                fp.traits.risk_tolerance,
                fp.traits.intuition_analysis_balance,
                fp.traits.time_horizon,
            ));
        }
    }

    md
}
